travis:
  secure:
    BINSTAR_TOKEN: AHhhFAXV5hhSBJw5hCaZZ4gGKBe7ls+wO5sWXnNxKy7iJtFyBL0SoE08ASsiui5odQguYbXW7q/N75tSJsJ/mdUAnkVAGA8wL9pIpwyt9HUk6kl2n0RZUbQN3a734V+6A9uPc2hAOztJs/dquMSGmJcn7lXzvIwAH4o3YHSYxr8Ix4UwAKYSpau9xsd+rGxc1vryTySH2Qw38rrj75xD03fBIbpzLE4A2PYaNg39lb3oaiJgIFuZcnFV5sB97Iu2u3W3bcau5EnXl8P8vNItj/uwK8AQpDZ8EvdmILuwsFshEUqkg0tQIhk8kVeSjnFAljU7fkSXp0lcYqT8SXAC+IwM6K9pPFnsfQNZzDjX3G/yA6oouisNEvZNFW4vWaDuu8RtzpCdLs7WUclp0JFTV7JZSlwr28bxlW5K0pa/1kTd32/iVHX5roeLLBvTAiF0qqstdKFpInfiwKahjjkFu7hculZIeC34RanX2AZ5j81hSqnBTBQt3IWaGFR46alufEWMM1ExBDyWK5h7HmbBv8VeIqKSLRGHPFj0rKEg4pS9lfwnnbYZq8GpYf6Nj3Gi09D6i4HjbX9FUxSuyWg65nQXFdDXiITpkyC87JdbjXmv5rEOctoq2Xj/EDEdoSm5t3OVA9fiBq9+T5dK6WTwZjG8BiFvV3F19wkzZmPTDA8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
